/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class flyingship_src_Backend */

#ifndef _Included_flyingship_src_Backend
#define _Included_flyingship_src_Backend
#ifdef __cplusplus
extern "C" {
#endif
#undef flyingship_src_Backend_MIN_PRIORITY
#define flyingship_src_Backend_MIN_PRIORITY 1L
#undef flyingship_src_Backend_NORM_PRIORITY
#define flyingship_src_Backend_NORM_PRIORITY 5L
#undef flyingship_src_Backend_MAX_PRIORITY
#define flyingship_src_Backend_MAX_PRIORITY 10L
/*
 * Class:     flyingship_src_Backend
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_flyingship_src_Backend_run
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
