/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class flyingship_src_FlyingShip */

#ifndef _Included_flyingship_src_FlyingShip
#define _Included_flyingship_src_FlyingShip
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     flyingship_src_FlyingShip
 * Method:    nativePrint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_flyingship_src_FlyingShip_nativePrint
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
