using namespace std::chrono_literals;

#define UNIQUE_IDS_N 4000
#define AGENT_Y_PADDING 20
#define DEFAULT_AGENT_SIZE 30
#define BACKEND_SLEEP_TIME 200ms
#define DEFAULT_SCREEN_WIDTH 800
#define DEFAULT_SCREEN_HEIGHT 600
#define DEFAULT_TIME_TICK_SPEED 200ms
#define ENV_PAUSE_SLEEP 1000ms