/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNI_flyingship_src_Backend */

#ifndef _Included_JNI_flyingship_src_Backend
#define _Included_JNI_flyingship_src_Backend
#ifdef __cplusplus
extern "C" {
#endif
#undef JNI_flyingship_src_Backend_MIN_PRIORITY
#define JNI_flyingship_src_Backend_MIN_PRIORITY 1L
#undef JNI_flyingship_src_Backend_NORM_PRIORITY
#define JNI_flyingship_src_Backend_NORM_PRIORITY 5L
#undef JNI_flyingship_src_Backend_MAX_PRIORITY
#define JNI_flyingship_src_Backend_MAX_PRIORITY 10L
/*
 * Class:     JNI_flyingship_src_Backend
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNI_flyingship_src_Backend_run
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
